elasticsearch:
  build: ./elasticsearch/
  ports:
    - "9200:9200"
    - "9300:9300"
  volumes:
    - "./elasticsearch/config/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties"
    - "./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    - "./elasticsearch/data/:/usr/share/elasticsearch/data/"
    - "./elasticsearch/logs/:/usr/share/elasticsearch/logs/"

kibana:
  build: ./kibana/
  ports:
    - "5601:5601"
  links:
    - elasticsearch:elasticsearch
  volumes:
    - "./kibana/config/kibana.yml:/kibana/config/kibana.yml"

logstash:
  build: ./logstash/
  links:
    - elasticsearch:elasticsearch
  volumes:
    - "./logstash/config/logstash.conf:/logstash/config/logstash.conf"
    - "./logstash/incoming_logs/:/logstash/incoming_logs/"
